language: python
python:
    - "3.6"
install:
    - pip install python-coveralls
script: 
    - python -m pytest nep_solvers_test.py -v --cov --cov-report=html
after_success:
    - coveralls
notifications:
email: false
