language: python
python:
    - "3.6"
install:
    - pip install python-coveralls
    - pip install --only-binary=scipy scipy
    - pip install --only-binary=matplotlib matplotlib
script:
    - python -m pytest test/nep_solvers_test.py
    - python -m pytest test/nep_classes_test.py
    - python -m pytest test/other_functions_test.py
after_success:
    - coveralls
notifications:
email: false
