language: python
python:
    - "3.6"
install:
    - pip install python-coveralls
    - pip install --only-binary=scipy scipy
script: 
    - python -m pytest nep_solvers_test.py
after_success:
    - coveralls
notifications:
email: false
